const express = require("express");
const cors = require("cors");
const morgan = require("morgan");
const api = require("./route/api.v1");
const errorHandler = require("./middlewares/errorHandler");
const notFound = require("./middlewares/notFound");
const app = express();
app.use(cors());
app.use(morgan("dev"));
app.use(express.json());
app.use("/api/v1", api);
app.use(errorHandler);
app.use(notFound);
module.exports = app;
